# version: "3.7"

services:

    # base:
    #     build:
    #         context: gears/base/.
    #         dockerfile: Dockerfile
    #     image: base:bullseye

    nginx:
        build:
            context: gears/nginx/.
            dockerfile: Dockerfile
            # additional_contexts:
            #     base_image: gears/base
        container_name: nginx_t
        image: nginx_t:0.0.1 
        networks:
            - transcendance
        ports:
            - 4243:443
            - 8080:80
        restart: on-failure
        depends_on:
            # - base
            - webapp
        

    webapp:
        build: 
            context : gears/webapp/.
            dockerfile: Dockerfile
        container_name: webapp
        image:  webapp
        volumes:
            - ./gears/webapp/src:/usr/local/src
            - /usr/local/src/node_modules
        networks:
            - transcendance
        expose:
            - "3000"
        restart: on-failure

networks:
    transcendance:
        driver: bridge

# volumes:
#     webapp:
#         driver: local
#         driver_opts:
#             type: none
#             o: 'bind'
#             device: './gears/webapp/src'
