version: "3.7"

services:

    nginx:
        build:
            context: gears/nginx/.
            dockerfile: Dockerfile
            additional_contexts:
                base_image: gears/base
        container_name: nginx_t
        image: nginx_t:0.0.1 
        networks:
            - transcendance
        ports:
            - 4243:443
            - 8080:80
        restart: on-failure
        depends_on:
            - webapp

    webapp:
        build: 
            context : gears/webapp/.
            dockerfile: Dockerfile
        container_name: webapp
        volumes:
            - ./webapp:/data
            - /data/etc
            - /data/node_modules
        image:  webapp
        networks:
            - transcendance
        expose:
            - "5000"
        restart: on-failure

    frontend:
        build: 
            context : gears/frontend/.
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            - ./frontend/src:/data
        image:  frontend
        networks:
            - transcendance
        expose:
            - "3000"
        restart: on-failure

    DB:
        build: 
            context : gears/DB/.
            dockerfile: Dockerfile
        container_name: DB
        volumes:
            - ./DB/src:/data
        image:  DB
        networks:
            - transcendance
        expose:
            - "9000"
        restart: on-failure

networks:
    transcendance:
        driver: bridge