services:

    nginx:
        build:
            context: gears/nginx/.
            dockerfile: Dockerfile
        container_name: nginx
        image: nginx_t:0.0.1 
        networks:
            - Solar_Cam
        ports:
            - 8080:80
            - 3000:443
        restart: on-failure
        depends_on:
            - backend
            - frontend

    backend:
        build: 
            context : gears/backend/.
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./gears/backend:/data
            - /data/node_modules
        environment:
            - APP_MODE=${APP_MODE}
            - DATABASE_URL=postgresql://user_admin:mon_password_secret@db:5432/db
        image:  backend
        networks:
            - Solar_Cam
        expose:
            - "3000"
        ports:
            - "5555:5555"
        depends_on:
            - db
            - frontend
        restart: on-failure

    frontend:
        build: 
            context : gears/frontend/.
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            - ./gears/frontend/src:/data 
            - /data/node_modules
        environment:
            - APP_MODE=${APP_MODE}
        image:  frontend
        networks:
            - Solar_Cam
        expose:
            - "5173"
        restart: on-failure

    db:
        build:
            context : gears/db/.
            dockerfile : Dockerfile
        container_name : db 
        volumes:
            - ./gears/db/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=user_admin
            - POSTGRES_PASSWORD=mon_password_secret
            - POSTGRES_DB=db
        networks:
            - Solar_Cam
        ports:
            - "5432:5432"
        restart: always
    
    go2rtc:
        image: alexxit/go2rtc
        container_name: go2rtc
        networks:
            - Solar_Cam
        env_file:
            - gears/go2rtc/.env  # Ceci charge automatiquement toutes les variables du .env
        # environment:
        #     - GARAGE_USER=${GARAGE_USER}
        #     - GARAGE_CODE=${GARAGE_CODE}
        #     - GARAGE_IP=${GARAGE_IP}
        #     - GARAGE_PORT=${GARAGE_PORT}
        ports:
            # - "8554:8554"
            - "1984:1984"
            - "8555:8555"
        volumes:
            - ./gears/go2rtc/go2rtc.yaml:/config/go2rtc.yaml
        restart: always
    

networks:
    Solar_Cam:
        driver: bridge