events{}
http
{
	include /etc/nginx/mime.types;
	tcp_nopush on;

    server
    {
        listen 80;
        # return 301 https://localhost:3000$request_uri;
		return 301 https://$host$request_uri;
    }

	server
	{
		listen 443 ssl;

		#root and index
		server_name		Solar-Cams localhost;
		# root			/var/www/wordpress;
		index			index.php index.html index.htm;

		#SSL/TLS conf
		ssl_certificate 	/etc/nginx/ssl/nginx.crt;
		ssl_certificate_key	/etc/nginx/ssl/nginx.key;
		ssl_protocols		TLSv1.2 TLSv1.3;
	
		http2_max_field_size	16k;
		http2_max_header_size	32k;
 

		proxy_intercept_errors on;

        location /
		{
			resolver 127.0.0.11 valid=30s;
			set $upstream_frontend http://frontend:5173;
    
    		proxy_pass $upstream_frontend;
			# proxy_pass http://frontend:5173;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;

		}
		location /go2rtc/ {
			resolver 127.0.0.11 valid=30s;
			set $upstream_go2rtc http://go2rtc:1984/;
    
    		proxy_pass $upstream_go2rtc;
			# proxy_pass http://go2rtc:1984/; # Note le slash à la fin
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
		}
		error_page 404 /404.html;
		location = /404.html
		{
			root /usr/share/nginx/html;
		}

		location /api {
			resolver 127.0.0.11 valid=30s;
			set $upstream_backend http://backend:3000;
    
    		proxy_pass $upstream_backend$request_uri;
        	# proxy_pass http://backend:3000;
    	}

	}
}